[package]
name = "telegram-onedrive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.30", default-features = false }
grammers-client = { version = "0.6.0", default-features = false }
grammers-mtsender = { version = "0.5.1", default-features = false }
grammers-session = { version = "0.5.2", default-features = false }
pico-args = { version = "0.5.0", default-features = false, features = [
    "short-space-opt",
] }
tokio = { version = "1.38.0", default-features = false, features = [
    "macros",
    "rt-multi-thread",
] }
