services:
  telegram-onedrive:
    container_name: telegram-onedrive
    image: hlf01/telegram-onedrive
    restart: always
    volumes:
      - telegram-onedrive-session:/session
      - telegram-onedrive-logs:/logs
      # - /path/to/*.crt:/ssl/server.crt
      # - /path/to/*.key:/ssl/server.key
    ports:
      - xxxx:8080
    environment:
      # - port=8080
      # - trace_level=info
      # - worker_num=5
      - server_uri=https://xxxxxxxx.com
      # - reverse_proxy=true
      - tg_bot_token=xxxxxxxxxx:xxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxx
      - tg_api_id=xxxxxxxx
      - tg_api_hash=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - tg_user_phone=+xxyyyyyyyyyyy
      # - tg_user_password=xxxxxxxx
      # - tg_user_name=xxxxxxxx
      - od_client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - od_client_secret=xxxxx~x.xxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - od_root_path=/xxxxxxxx
      # - auto_delete=true

volumes:
  telegram-onedrive-session:
  telegram-onedrive-logs:
